### ISSUE TITLE
Issue when scrolling page

### ISSUE THREAD

**Issue by anteadea** [code-orange/telemachy#5]
Hi
I have an issue when I scroll my page. The highlight item with description isn't following the items on the page.

Can you help me to fix it please?

![image](https://user-images.githubusercontent.com/37408909/37480921-bc784bba-2880-11e8-87e1-48759351a828.png)

**Comment by timvdalen** [comment]
Hmm, I can't seem to reproduce this. The highlight box is tied to the page coordinates of the selected element, so it should just stay in the same place when you scroll.

Do you have a scrolling container? That might cause this since then the page coordinates of the selected element might change. What happens when you move the tour component into the scrolling container?

**Comment by timvdalen** [comment]
I was able to reproduce this in Chrome on OS X.

* Start a tour
* View some steps, highlight some elements
* Scroll
* During scrolling, the element stays highlighted correctly
* Go next
* The next element is highlighted where it was when the tour began, not where it is now.

**Comment by anteadea** [comment]
Hello,
You're right, I have a scroll container, and it's the same result when I move the tour component inside.

When you calculate the coordinates of the overlay, you use 'document.body.scrollTop', I try with 'window.scrollY' instead and this solves the problem.

Do you think you can fix it or do you prefer that I submit a PR?

**Comment by timvdalen** [comment]
If you could submit a PR, that'd be great! If not, I think I can get around to this somewhere next week as I've run into this with another project myself.

**Comment by anteadea** [comment]
I submited a [PR ](https://github.com/code-orange/telemachy/compare/master...anteadea:master)
